version: "3.8"

services:
  postgres:
    image: postgres:14.2
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - PGSDATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  testdb_postgres:
    image: postgres:14.2
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: testdb_postgres
    command: -p 5433

  server:
    container_name: updateservice
    environment:
      - UPDATE_SRV_DB_CONNECTION_STRING=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    build:
      context: ./
      cache_from:
        - ${IMAGE}
    image: ${IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  PGSDATA:
